EXCEL_NAME = "../search_excel/data/saimu_data.xlsx"
BS_SHEET = "BS"
PL_SHEET = "PL"
TAX_LATE_SHEET = "軽減税率・経過措置対象コード"
GROUP_SHEET = "特例子会社のグループ認定制度"
COM_HOUSE_SHEET = "社宅関連"
SHEET_NAMES = [BS_SHEET, PL_SHEET, TAX_LATE_SHEET, GROUP_SHEET, COM_HOUSE_SHEET]
N_INCLUDE_WORD = 860
SELECT_DATA_PATH = "../wiki_sentences_860.pickle"
SEPARATOR = "。"
TRAIN_DATA_PATH = "../train_data_860.pickle"
